{
  "branches": [
    "main",
    "master",
    "*.x"
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "types": [
            { "type": "feat", "section": "Features", "hidden": false },
            { "type": "fix", "section": "Bug Fixes", "hidden": false },
            { "type": "perf", "section": "Performance Improvements", "hidden": false },
            { "type": "refactor", "section": "Code Refactoring", "hidden": false },
            { "type": "test", "section": "Tests", "hidden": false },
            { "type": "build", "section": "Build System", "hidden": false },
            { "type": "ci", "section": "Continuous Integration", "hidden": false },
            { "type": "docs", "section": "Documentation", "hidden": false },
            { "type": "style", "section": "Styles", "hidden": false },
            { "type": "chore", "section": "Chores", "hidden": false },
            { "type": "revert", "section": "Reverts", "hidden": false }
          ]
        }
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": [
          "CHANGELOG.md"
        ]
      }
    ],
    "@semantic-release/github"
  ]
}
